name: Release & Publish Firefox Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: 'v2.0'
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Sign & Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install web-ext
        run: npm install --no-save web-ext

      - name: Lint Extension
        run: npx web-ext lint

      - name: Submit to AMO
        continue-on-error: true
        run: |
          npx web-ext sign \
            --channel=listed \
            --api-key="${{ secrets.AMO_JWT_ISSUER }}" \
            --api-secret="${{ secrets.AMO_JWT_SECRET }}" \
            --timeout=300000
